CREATE TABLE webhooks (
    id CHAR(36) NOT NULL DEFAULT (UUID()),
    endpoint_url VARCHAR(255) NOT NULL,
    secret_key VARCHAR(255),
    event_type VARCHAR(50) NOT NULL DEFAULT 'PAYMENT_CREATED',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT pk_webhook PRIMARY KEY (id)
);